version: 2
jobs:
  build:
    working_directory: ~/circleci-coastal-image-browser
    docker:
      - image: circleci/python:3.6-browsers  # primary container for the build job
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # install dependencies
            pip install -r requirements.txt
      - run:
          command: |
            python manage.py test
