version: 2
jobs:
  build:
    working_directory: ~/circleci-coastal-image-browser
    docker:
      - image: circleci/python:3.8-browsers  # primary container for the build job
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # install dependencies
            sudo pip install -r requirements.txt
            sudo pip install coverage
      - run:
          command: |
            coverage run manage.py test
            coverage report
            coverage html
      - store_artifacts:
          path: htmlcov
