# Generated by Django 2.1.4 on 2019-02-21 10:01

from django.db import migrations, models
from main.settings import IS_TESTING


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('location', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('site', models.CharField(max_length=16)),
                ('epoch', models.IntegerField()),
                ('camera', models.IntegerField()),
                ('image_type', models.CharField(db_column='type', max_length=16)),
                ('day_minute', models.SmallIntegerField(blank=True, db_column='dayminute', null=True)),
                ('inarchive', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Images',
                'ordering': ('-epoch', 'camera'),
                'managed': IS_TESTING,
            },
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('site', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('utcoffset', models.IntegerField(blank=True, db_column='utcOffset', null=True)),
                ('mincam', models.IntegerField(blank=True, db_column='minCam', null=True)),
                ('maxcam', models.IntegerField(blank=True, db_column='maxCam', null=True)),
                ('accessgroup', models.IntegerField(blank=True, db_column='accessGroup', null=True)),
                ('openaccess', models.IntegerField(blank=True, db_column='openAccess', null=True)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('epochstart', models.IntegerField(blank=True, db_column='epochStart', null=True)),
            ],
            options={
                'db_table': 'Sites',
                'ordering': ('site',),
                'managed': IS_TESTING,
            },
        ),
    ]
