# Generated by Django 2.2.2 on 2019-06-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostRecentImages',
            fields=[
                ('location', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('site', models.CharField(max_length=16)),
                ('camera', models.IntegerField()),
                ('image_type', models.CharField(db_column='type', max_length=16)),
            ],
            options={
                'db_table': 'MostRecentImages',
                'ordering': ('image_type', '-camera'),
                'managed': False,
            },
        ),
    ]
